export const Shifts = {
          sameDepartmentSameDay: [
            {
                day: 4,
                department: "service",
                role: "service leader",
                start: 8,
                end: 14,
                people: 2,
                hourly: 12
              }, 
              {
                day: 4,
                department: "service",
                role: "service support",
                start: 9,
                end: 15,
                people: 1,
                hourly: 12,
              },
      ], 
      sameDepartmentSameRoleDiffDays: [
          {
            day: 0,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          },
          {
            day: 1,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          },
          {
            day: 2,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          },
          {
            day: 3,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          },
          {
            day: 4,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          },
          {
            day: 5,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          },
          {
            day: 6,
            department: "bake off",
            role: "kettle",
            start: 5,
            end: 9,
            people: 1,
            hourly: 12,
          }
      ], 
      sameDeptTwoRoles: [
        {
          day: 0,
          department: "bake off",
          role: "kettle",
          start: 5,
          end: 9,
          people: 1,
          hourly: 12,
        },
        {
          day: 1,
          department: "bake off",
          role: "starters",
          start: 5,
          end: 9,
          people: 1,
          hourly: 12,
        },
    ], 
} 